### PR TITLE
feat: Support Python lambdas (local branch)

### PR DESCRIPTION
**Pull request by ServerlessLife**
Fixes #

### CODE REVIEW

**Comment by Lewenhaupt** [comment]
@ServerlessLife We can pre-build the python layer(s) but we would have to do so for each python version and architecture combination we want to support. The reason is that both awscrt and awslambdaric creates dynamically linked binaries.
I think a better solution might be to add an option for the user to configure their configuration for how the layer is built and we then simply point to the layer code with those instructions. I.e. the user could add all the properties of LayerVersion into the call to ServerlessSpy and we would then respect that. 
That way we would support the flexible use of docker (i.e. allowing the user to mix python versions and architectures) or use a native approach and then be in control of how it's built themselves. We could even support a default config for LayerVersion with python, that would simply use whatever python version the user has installed. Does increase the need for documentation but I think it would be much easier to maintain. Python is a bit trickier to bundle correctly as compared to node imo. At least when considering multiple versions and architectures.

**Comment by Lewenhaupt** [comment]
An additional option would be to piggy back off of https://github.com/keithrozario/Klayers and simply add a PR for adding awslambdaric, awscrt, and aws-iot-sdk. That way we could include them as a simple layer (via the known arns, just have to hardcode them) and then simply adding only the interceptor.py in a layer (which would not be any different for any version or architecture).

**Comment by ServerlessLife** [comment]
I do not know anything about Python, and I am surprised to learn that there is such an issue with dependencies. If we can not avoid Docker, then we can not avoid it. Adding additional parameters to ServerlessSpy seems a bit awkward. Using Klayers seems like a great idea. 

It is interesting that [AWS instructions](https://docs.aws.amazon.com/lambda/latest/dg/python-package.html#python-package-create-dependencies) do not require any bundling, but most of the other links I found do.

We could also peek at how Lumigo does the Layer:
https://github.com/lumigo-io/python_tracer/blob/master/scripts/deploy.sh

**Comment by Lewenhaupt** [comment]
@ServerlessLife Sorry I've not gotten back to this yet, been busy with work and life-stuff 😅 
I've been thinking a bit more on the possibility to package things as layers and I really don't think packaging them ourselves is an option (there is a reason aws-cdk provides a docker image that does it). And whilst using [KLayers ](https://github.com/keithrozario/Klayers) would be an option (after providing a PR adding the missing layers) it would mean having to include 4 layers for each lambda, which means that it would break for anyone trying to apply it to a lambda with 2 or more layers. 
Let me know what you think.

**Comment by ServerlessLife** [comment]
@Lewenhaupt 
No worries. Thank you for still sticking with this feature. 💪 👏 

If there is no sensible solution to avoid Docket, then there is no need to resort to an even more complicated solution.

**Comment by markostru** [comment]
> running the tests related to python if you want such that there's and easier way of running the tests without docker. 

No need for me. You can if you prefer so.

> Also, are we able to publish beta versions to npm? 

I have never done that, so I do not know.

**Comment by Lewenhaupt** [comment]
Alright I'll see if I can figure out how to publish betas 😊

**Comment by Lewenhaupt** [comment]
@ServerlessLife Started testing a bit more and noticed a rate-limiting issue with getting the IoT endpoint so I'm moving it to cdkOutput instead (same as with the wsUrl before). Also realised that the cli wasn't working now with IoT so I'm trying to fix that too, hence this taking a bit more time hehe.

**Comment by ServerlessLife** [comment]
@Lewenhaupt 
Thank you for your hard work. 🙏 

How come that you hit IoT limits. Is that so low? How much data did you send through?

**Comment by Lewenhaupt** [comment]
Not on the iot messages themselves, just the describe iot endpoint sdk call which I used to get the endpoint to connect to. So I retrieve it during deploy time instead now which works much better. 😊

**Comment by Lewenhaupt** [comment]
@ServerlessLife I've gotten the cli up-to speed and I think I've altered the relevant docs.
Let me know when you've had a chance to look at it.
I've ran used it locally against my project at work and the transition to the new version was smooth and test ran as expected. I encountered some issues with a Custom Resource that retrieved the iot-endpoint leading to a bit of ugliness when filtering the nodes which we should spy on but I wasn't able to find a better solution right now.

**Comment by Lewenhaupt** [comment]
@ServerlessLife I'm going to make a slight improvement to avoid having to create two layers for python functions as it's a bit overkill.

**Comment by Lewenhaupt** [comment]
Fixed the additional layer that was created such that we limit it to only one layer to reduce the risk of users reaching the cap.

**Comment by ServerlessLife** [comment]
@Lewenhaupt 
Thank you very much. I will try to take a look at it at the beginning of next week.

**Comment by Lewenhaupt** [comment]
Thanks @ServerlessLife 😊

**Comment by ServerlessLife** [comment]
Hey @Lewenhaupt!

You did truly amazing work. Astounding, really. :muscle: :muscle: :muscle: 

I did three tiny commits on documentation: c52fb4c0d17a4e931fe66eee960a5f52cc53935e, bd2ed520f96c790350ef95a4aa7b43e5fe749b76, 41356c7dd4b9ed80829edf5b4ddcce6cf1f7a4ba
I fixed my name, removed you from contributors as you are co-author now, and fixed the documentation.

I found one issue that we should resolve. You added `scope` on the listener, which translates to an IoT topic. Since this will be the same for each project instance/environment, there will be an issue if two environments of the same project run on the same AWS account. There are multiple solutions. The simplest is probably to use the CloudFront stack name as a topic. What do you think?

**Comment by ServerlessLife** [comment]
Another thing. I changed the major version to 2. I think this change is big enough for this.

**Comment by Lewenhaupt** [comment]
> Hey @Lewenhaupt!
> 
> You did truly amazing work. Astounding, really. 💪 💪 💪
> 
> I did three tiny commits on documentation: [c52fb4c](https://github.com/ServerlessLife/serverless-spy/commit/c52fb4c0d17a4e931fe66eee960a5f52cc53935e), [bd2ed52](https://github.com/ServerlessLife/serverless-spy/commit/bd2ed520f96c790350ef95a4aa7b43e5fe749b76), [41356c7](https://github.com/ServerlessLife/serverless-spy/commit/41356c7dd4b9ed80829edf5b4ddcce6cf1f7a4ba) I fixed my name, removed you from contributors as you are co-author now, and fixed the documentation.
> 
> I found one issue that we should resolve. You added `scope` on the listener, which translates to an IoT topic. Since this will be the same for each project instance/environment, there will be an issue if two environments of the same project run on the same AWS account. There are multiple solutions. The simplest is probably to use the CloudFront stack name as a topic. What do you think?

Thanks @ServerlessLife :)

Thanks for the fixes and sorry I put your full name, saw it in git blame and added it when I added mine.

Yeah the scope is set by the interceptor such that each stack publishes on it's own topic, and it's based on the root stack, so if that stack would be deployed twice in the same account the names would be different. However I do not add that to the cdkOutput which I think would be a good addition and allow some easier config for the user. It is possible to set the scope on the listener (which I've done in the e2e.test.ts for example), but it is hardcoded and not retrieved from the output which isn't really optimal. I should also add some documentation on this. I think that should cover the scenario you described? Let me know if it doesn't and if I misinterpreted you somehow, or if we should add something more to the topics. I tried to keep the changes backwards compatible.

**Comment by ServerlessLife** [comment]
Regarding the stack/topic (which is equal to the stack name), we can embed the name into the `ServerlessSpyWsUrl`.

For example, for the stack `ServerlessSpyE2e`:
`ServerlessSpyWsUrl` is now `xxxxxxxxxxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com`
we can make it `xxxxxxxxxxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com/ServerlessSpyE2e`
and nothing would essentially change compared to version 1.

When you read the `ServerlessSpyWsUrl` you split it and pick the the `url` and `scope`.

**Comment by Lewenhaupt** [comment]
> It is a funny story why I do not put my surname anywhere. At the beginning of my career, I wrote a really great article. There is a person with the same name and surname who was also an expert on that subject. Instead of me, he was contacted and got an amazing job at a big well, well-known international company. 💸 💸 💸 💸 🤑 🤑 🤑 
> 
> I will double-check regarding the IoT topic/scope.
> 

Oh wow that sucks!

Let me know if I misunderstood something and I'll get on fixing it 😊

**Comment by Lewenhaupt** [comment]
> Regarding the stack/topic (which is equal to the stack name), we can embed the name into the `ServerlessSpyWsUrl`.
> 
> For example, for the stack `ServerlessSpyE2e`:
> `ServerlessSpyWsUrl` is now `xxxxxxxxxxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com`
> we can make it `xxxxxxxxxxxxxxxxxx-ats.iot.eu-west-1.amazonaws.com/ServerlessSpyE2e`
> and nothing would essentially change compared to version 1.
> 
> When you read the `ServerlessSpyWsUrl` you split it and pick the the `url` and `scope`.
> 
> 
> 
> 
> 

Yeah I like that idea! Good suggestion, give me a couple minutes and I'll have a fix in place 😊

**Comment by ServerlessLife** [comment]
Hey @Lewenhaupt 
I do not know if you intent to do any other changes, but I think we are good to merge & deploy.

Seriously, I can't thank you enough for the incredible work you have done. 🙏

Kudos to the quality of your code, ideas, and speed of development. 💪🏅

**Review by markostru — APPROVED** [review]

**Comment by Lewenhaupt** [comment]
> Hey @Lewenhaupt I do not know if you intent to do any other changes, but I think we are good to merge & deploy.
> 
> Seriously, I can't thank you enough for the incredible work you have done. 🙏
> 
> Kudos to the quality of your code, ideas, and speed of development. 💪🏅

Thanks a lot for the kind words @ServerlessLife, means a lot to know you're happy with the work! And thanks for taking the time to review properly through the process and being open to changes. I would not have done this if you hadn't laid such a solid ground work! 

I'm happy with the state of it now :) I might pick up the http interceptor task (https://github.com/ServerlessLife/serverless-spy/issues/11) if I have the time because I think that would be a really great feature. Even better if I can also find a way to do it for the python implementation as well. Would be really cool if we could inject mocks into the lambda because I have some scenarios where I currently have to setup another API Gateway and point all calls to that, but that is really yanky and will be horrible when the number of paths I need to mock increases.

**Comment by Lewenhaupt** [comment]
Ah damnit, I think I've missed some conf for the release action. I'll create another branch and adapt it to the changes needed.

**Comment by markostru** [comment]
@Lewenhaupt 
As you saw, the system deployed itself. 

I already tested it on my sample app, and it works.

I will write some Tweets & LinkedIn posts once I have a bit of time.

**Comment by Lewenhaupt** [comment]
Awesome, thanks @ServerlessLife 😊

**Pull request merged**
