### PR TITLE
feat: Support Python lambdas

### PR DESCRIPTION
**Pull request by Lewenhaupt**
@ServerlessLife I've had to upgrade Typescript version to deal with a jsii issue introduced by aws-python-lambda. I also raised the cdk-lib version to get the proper Runtime class for Python 10 from aws-lambda.
I have not done anything to disable IoT when no clients are attached but as we spoke about it's probably not anything critical as the cost will be minimal anyway.

Let me know what you think of the implementation. I hope I have covered all of the tests that are relevant.

### CODE REVIEW

**Comment by ServerlessLife** [comment]
You are amazing! 

I will review the PR over the next weekend. I hope that is OK with you.

**Comment by Lewenhaupt** [comment]
Of course! 😊

**Comment by ServerlessLife** [comment]
Hey Hugo,

I apologize for not having time to review your PR before. I have many obligations and do not have as much time as I used to. Plus it was re:Invent.

I reviewed your code, and you did an absolutely amazing job.

Unfortunately, some of the tests fail. For example:
```
 FAIL  test/cdk/test/snsToSqs.test.ts (47.527 s)
    Failed to bundle asset Test/ServerlessSpy/PythonExtension/Code/Stage, bundle output is located at 
```

That is strange. Why would it need to bundle the Python code since it is Node.js only test. I presume that when the test builds the CDK to make a snapshot, it bundles the Python extensions. But that should be bundled when ServerlessSpy is built, not when ServerlessSpy is used in a new stack. Could you look at that issue?

I granted you permission on the repository so you can merge the PR yourself when you are ready.

Before you do:
 - You can add yourself as an co-author to Readme and the webpage. How would you like to do that it is up to you. But do not remove me :laughing:
 - We need to bump the version. I suggest to move to 2.0. The setting is in tasks.json -> release -> env -> MAJOR
 - We need to update the documentation to reflect the new changes and instructions on how to migrate from 1.x to 2.0

**Comment by Lewenhaupt** [comment]
No problem at alla Marko!

Hmm that's odd, it passed when I ran the tests before submitting the PR, but I'll have a look and see what's wrong. And yeah I agree it shouldn't include any python code of there is no python lambda included in the tests.

Haha yeah I promise I'll not remove you 😂
I think the diagram need to be updated as well right? Which service did you use to make it?

**Comment by ServerlessLife** [comment]
For the diagram, I used https://app.diagrams.net/, which is also available as a VsCode extension:
https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio

The file is `doc/concept.png`
If you want to edit it in VsCode rename it to `concept.drawio.png`.

This is an amazing tool. Although the file is `png` it allows you to edit it because all the vector data is in metadata.

**Comment by Lewenhaupt** [comment]
@ServerlessLife Would you mind sharing some more of the error logs you get when running the tests? I can't seem to reproduce it on my machine, all tests pass. Is it possible this is docker-related? The python bundling in cdk requires docker.

I did however find why that specific test suddenly ran python-code. The test itself was referencing the SnsToLambdaStack instead of the SnsToSqsStack that it was testing.

**Comment by Lewenhaupt** [comment]
Also, I can't see any Author section in the README.md? Is it in some other file? Or should I add it?

**Comment by ServerlessLife** [comment]
Here is full error log 
[test_output.txt](https://github.com/ServerlessLife/serverless-spy/files/13539588/test_output.txt)

**Comment by ServerlessLife** [comment]
Regarding the author section. Currently, there is no such section. There is just my name in the header. You can make an author chapter at the end, move my name, and add yours. Or you can do something else.

**Comment by Lewenhaupt** [comment]
> Here is full error log 
> [test_output.txt](https://github.com/ServerlessLife/serverless-spy/files/13539588/test_output.txt)
> 

Hmm, that seems like a docker issue since it seems to fail when trying to write the asset output from the docker container. Are you running docker as another user or similar?

**Comment by ServerlessLife** [comment]
It is a Docker issue, but there should not be any Docket at that point. Looks like CDK is using Docker to bundle Python code, but it should not need to bundle it at all. 

I am using Ubuntu. That could be a reason for a different output that you might have.

**Comment by ServerlessLife** [comment]
Hey Hugo,

I just found out the following :disappointed:  : 
> By default, pull-request builds don't get access to the secrets to prevent people from using the pull requests to exfiltrate your secrets through a change that reads the environment and sends the data somewhere else.
https://stackoverflow.com/questions/73866908/github-actions-main-repository-secret-not-picked-up-from-pull-request-build

So, in fact, you do not have access to secrets. I will look into a possible solution in the evening. I will also dive deeper into the Docker issue.

**Comment by Lewenhaupt** [comment]
> Hey Hugo,
> 
> I just found out the following :disappointed:  : 
> > By default, pull-request builds don't get access to the secrets to prevent people from using the pull requests to exfiltrate your secrets through a change that reads the environment and sends the data somewhere else.
> https://stackoverflow.com/questions/73866908/github-actions-main-repository-secret-not-picked-up-from-pull-request-build
> 
> So, in fact, you do not have access to secrets. I will look into a possible solution in the evening. I will also dive deeper into the Docker issue. 

Yeah I suspected something like that, and it kind of makes sense. I can run it in my fork and set up my own secrets if you want.

Awesome 👍

**Comment by ServerlessLife** [comment]
It turns out the permissions work if the PR branch is from the local repo. So I merged your PR to a local branch and created a new PR and secrets works: https://github.com/ServerlessLife/serverless-spy/pull/23

You can work on that PR or create a new one if you prefer.

**Comment by ServerlessLife** [comment]
I figured out why the Docker gets involved when running the tests.

The [`PythonLayerVersion`](https://docs.aws.amazon.com/cdk/api/v2/docs/@aws-cdk_aws-lambda-python-alpha.PythonLayerVersion.html) uses Docket for bundling. It is triggered even if you just use the construct that uses the `PythonLayerVersion`. So we should use the raw [`LayerVersion`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda.LayerVersion.html) and use pre-bundled files (if bundling is needed at all). That should not be a big change.

A similar problem is with TypeScript. If it is not compiled to JS, then it runs a Docker to compile ("transpile") if the user does not have `esbuild` installed in the `project.json.` That's why I precompile all the TypeScript that is used in Lambda on the Lambda layer.

**Comment by Lewenhaupt** [comment]
Yes docker is used to build the python layers. I'm not sure it's wise to prebundle the python layers (they are pretty sensitive to the environment being used to build them, especially awscrt breaks if the environment isn't correct). But I'll have a look. Could probably prebundle them with docker and use the output directly when building the layers.

**Comment by Lewenhaupt** [comment]
Closing as it has been handled in a local branch and PR to the project instead of from a fork.

**Pull request closed without merging**
