### PR TITLE
fix: Fix an issue with cdkstack not working when first stack did not contain ServerlessSpyWsUrl

### LINKED ISSUE #58: cdkstack option not considered in initial cli connection
The cdkstack option is not considered when the cli makes the initial connection causing it to fail if the ServerlessSpyWsUrl is not in the first stack.
@markostru I can fix this tomorrow.

### PR DESCRIPTION
**Pull request by Lewenhaupt**
Fixes #58

### CODE REVIEW

**Comment by Lewenhaupt** [comment]
@markostru I changed the stackList endpoint too such that it always returns all stacks because I think it got a bit confusing that picking which stack contained the conf would disable selecting other stacks.

**Comment by ServerlessLife** [comment]
@Lewenhaupt 
Thank you very much. I have been buzzy for the last two days, but I will be able to check the PR and issues tomorrow.

Thank you for understanding.

**Comment by Lewenhaupt** [comment]
No rush! I'll have a pr up with a fix for the other issue tomorrow or later
tonight.

Den ons 25 dec. 2024 18:40Marko ***@***.***> skrev:

**Review by ServerlessLife — APPROVED** [review]
@Lewenhaupt 
Thank you very much for fixing this.

**Pull request merged**
